name: Build and deploy package

on:
  push:
    branches:
      - main
env:
  # Project name to pack and publish
  PROJECT_NAME: Gravatar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test

      - name: Create the package
        run: dotnet pack --configuration Release

      - name: Publish
<<<<<<< HEAD
        run: dotnet nuget push "./Gravatar/${{ env.PROJECT_NAME }}/bin/Release/*.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
=======
        run: dotnet nuget push "./Gravatar/bin/Release/Gravatar.1.0.0.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
>>>>>>> a90098f7b73eaffbacff8df4ce7ec19a0c9478eb
